dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_esignet:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet.git
    branch: release-1.5.x
