keycloak:
  realms:
    # realm
    mosip:
      realm_config:
        "realm": 'mosip'
        "enabled": 'True'
        "accessCodeLifespan": 7200
        "accessCodeLifespanLogin": 1800
        "accessCodeLifespanUserAction": 300
        "accessTokenLifespan": 86400
        "accessTokenLifespanForImplicitFlow": 900
        "actionTokenGeneratedByAdminLifespan": 43200
        "actionTokenGeneratedByUserLifespan": 300
        "passwordPolicy": "length(8)"
        "resetPasswordAllowed": 'True'
        "bruteForceProtected": 'True'
        "permanentLockout": 'False'
        "maxFailureWaitSeconds": 900
        "minimumQuickLoginWaitSeconds": 60
        "waitIncrementSeconds": 300
        "quickLoginCheckMilliSeconds": 1000
        "maxDeltaTimeSeconds": 600
        "failureFactor": 5
        # "attributes":
        #   "frontendUrl": ''
        "loginTheme": "mosip"
        "accountTheme": "mosip"
        "adminTheme": "mosip"
        "emailTheme": "mosip"
        "browserSecurityHeaders":
          "contentSecurityPolicy": "frame-src 'self' https://www.google.com; frame-ancestors 'self'; object-src 'none';"
        # "smtpServer":
        #   "password": ""
        #   "starttls": "false"
        #   "auth": "true"
        #   "port": "465"
        #   "host": "smtp.gmail.com"
        #   "from": ""
        #   "ssl": "true"
        #   "user": ""
      roles:
        - PARTNER_ADMIN
        - offline_access
        - uma_authorization
        - PUBLISH_OIDC_CLIENT_CREATED_GENERAL
        - PUBLISH_OIDC_CLIENT_UPDATED_GENERAL
        - PUBLISH_APIKEY_APPROVED_GENERAL
        - PUBLISH_APIKEY_UPDATED_GENERAL
        - PUBLISH_CA_CERTIFICATE_UPLOADED_GENERAL
        - PUBLISH_MISP_LICENSE_GENERATED_GENERAL
        - PUBLISH_MISP_LICENSE_UPDATED_GENERAL
        - PUBLISH_PARTNER_UPDATED_GENERAL
        - PUBLISH_POLICY_UPDATED_GENERAL
        - ZONAL_ADMIN
        - GLOBAL_ADMIN
        - CREDENTIAL_REQUEST
        - CREATE_SHARE
        - DEVICE_PROVIDER
        - PARTNER
        - ID_AUTHENTICATION
        - PMS_ADMIN
        - PMS_USER
        - REGISTRATION_PROCESSOR
        - SUBSCRIBE_OIDC_CLIENT_CREATED_GENERAL
        - SUBSCRIBE_OIDC_CLIENT_UPDATED_GENERAL
        - CREDENTIAL_PARTNER
        - PUBLISH_CREDENTIAL_STATUS_UPDATE_GENERAL
        - PUBLISH_REGISTRATION_PROCESSOR_WORKFLOW_COMPLETED_EVENT_GENERAL
        - PUBLISH_REGISTRATION_PROCESSOR_WORKFLOW_PAUSED_FOR_ADDITIONAL_INFO_EVENT_GENERAL
        - SUBSCRIBE_CREDENTIAL_ISSUED_INDIVIDUAL
        - SUBSCRIBE_REGISTRATION_PROCESSOR_WORKFLOW_COMPLETED_EVENT_GENERAL
        - SUBSCRIBE_REGISTRATION_PROCESSOR_WORKFLOW_PAUSED_FOR_ADDITIONAL_INFO_EVENT_GENERAL
      client_scopes:
        - name: add_oidc_client
          description: Scope required to create OIDC client
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
        - name: update_oidc_client
          description: ''
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
        - name: get_certificate
          description: Scope required to create OIDC client
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
        - name: upload_certificate
          description: ''
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
        - name: send_binding_otp
          description: Scope required to create OIDC client and mpartner-default-mobile client
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
        - name: wallet_binding
          description: Scope required to create mpartner-default-mobile client
          protocol: openid-connect
          "Include In Token Scope": on
          attributes: {
            display.on.consent.screen: "false",
            include.in.token.scope: "true"
          }
      clients:   
        - name: mosip-pms-client
          mappers: []
          saroles:
            - PARTNER_ADMIN
            - PUBLISH_OIDC_CLIENT_CREATED_GENERAL
            - PUBLISH_OIDC_CLIENT_UPDATED_GENERAL
            - PUBLISH_APIKEY_APPROVED_GENERAL
            - PUBLISH_APIKEY_UPDATED_GENERAL
            - PUBLISH_CA_CERTIFICATE_UPLOADED_GENERAL
            - PUBLISH_MISP_LICENSE_GENERATED_GENERAL
            - PUBLISH_MISP_LICENSE_UPDATED_GENERAL
            - PUBLISH_PARTNER_UPDATED_GENERAL
            - PUBLISH_POLICY_UPDATED_GENERAL
            - ZONAL_ADMIN
            - CREATE_SHARE
            - DEVICE_PROVIDER
            - PARTNER
            - PMS_ADMIN
            - PMS_USER
            - REGISTRATION_PROCESSOR
          assign_client_scopes:
            - update_oidc_client
            - add_oidc_client
            - get_certificate
            - upload_certificate
        - name: mpartner-default-auth
          mappers: []
          saroles:
            - SUBSCRIBE_OIDC_CLIENT_CREATED_GENERAL
            - SUBSCRIBE_OIDC_CLIENT_UPDATED_GENERAL
          assign_client_scopes:
            - update_oidc_client
            - add_oidc_client
        - name: mosip-ida-client
          mappers: []
          saroles:
            - CREDENTIAL_REQUEST
            - GLOBAL_ADMIN
            - ID_AUTHENTICATION
            - SUBSCRIBE_OIDC_CLIENT_CREATED_GENERAL
            - SUBSCRIBE_OIDC_CLIENT_UPDATED_GENERAL
        - name: mosip-deployment-client
          saroles:
            - ID_AUTHENTICATION
            - GLOBAL_ADMIN
            - PARTNER_ADMIN
            - uma_authorization
            - offline_access
        - name: mpartner-default-mobile
          mappers: [ ]
          saroles:
            - CREDENTIAL_PARTNER
            - SUBSCRIBE_REGISTRATION_PROCESSOR_WORKFLOW_COMPLETED_EVENT_GENERAL
            - SUBSCRIBE_REGISTRATION_PROCESSOR_WORKFLOW_PAUSED_FOR_ADDITIONAL_INFO_EVENT_GENERAL
            - PUBLISH_REGISTRATION_PROCESSOR_WORKFLOW_COMPLETED_EVENT_GENERAL
            - PUBLISH_CREDENTIAL_STATUS_UPDATE_GENERAL
            - PUBLISH_REGISTRATION_PROCESSOR_WORKFLOW_PAUSED_FOR_ADDITIONAL_INFO_EVENT_GENERAL
            - SUBSCRIBE_CREDENTIAL_ISSUED_INDIVIDUAL
          assign_client_scopes:
            - send_binding_otp
            - wallet_binding
