modules:
  esignet:
    enabled: true
    image:
      repository: mosipdev/apitest-esignet
      tag: release-1.5.x
      pullPolicy: Always

extraEnvVarsCM:
  - esignet-global
  - s3
  - keycloak-host
  - db
  - apitestrig

extraEnvVarsSecret:
  - apitestrig-esignet-apitestrig
  - s3-esignet-apitestrig
  - keycloak-client-secrets
  - postgres-postgresql

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi

   apitestrig:
  configmaps:
    apitestrig:

      # Wait time (in milliseconds) after UIN generation in IDREPO before proceeding
      uinGenerationProcessingDelayTimeInMilliSeconds: "{{ .Values.uinGenerationProcessingDelayTimeInMilliSeconds | default 90000 }}"
      # Wait time (in milliseconds) after VID generation in Resident before proceeding
      vidGenerationProcessingDelayTimeInMilliSeconds: "{{ .Values.vidGenerationProcessingDelayTimeInMilliSeconds | default 90000 }}"
      # Maximum retry attempts for UIN availability check during OTP generation
      uinGenMaxLoopCount: "{{ .Values.uinGenMaxLoopCount | default 20 }}"
