modules:
  esignet:
    enabled: true
    image:
      repository: mosipid/apitest-esignet
      tag: 1.6.2
      pullPolicy: Always

extraEnvVarsCM:
  - esignet-global
  - s3
  - keycloak-host
  - db
  - apitestrig

extraEnvVarsSecret:
  - apitestrig-esignet-apitestrig
  - s3-esignet-apitestrig
  - keycloak-client-secrets
  - postgres-postgresql

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi

