#image:
#  registry: docker.io
#  repository: mosipdev/partner-onboarder
#  tag: develop

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

onboarding:
  modules:
    - name: esignet
      enabled: true

  # If you want to override configmaps or secrets, uncomment and modify.
  # configmaps:
  #   s3:
  #     s3-host: 'http://minio.minio:9000'
  #     s3-user-key: 'admin'
  #     s3-region: ''
  #
  #   onboarder-namespace:
  #     ns_mimoto: mimoto
  #     ns_esignet: esignet
  #     ns_signup: signup
  #
  # secrets:
  #   s3:
  #     s3-user-secret: 'password'

  #volumes:
  #  reports:
  #    name: onboarder-reports
  #    storageClass: nfs-csi
  #    accessModes:
  #      - ReadWriteMany
  #    size: 10Mi
  #    existingClaim: ""
  #    mountDir: /home/mosip/reports
  #    nfs:
  #      path: /srv/nfs/mosip/<sadbox>/onboarder
  #      server: <nfs host>

extraEnvVarsCM: []
extraEnvVarsSecret: []